user:
  admin: #管理员用户id,可以添加多个
    - 123456789
    - 456789456
  alist_host: "http://127.0.0.1:5244" #alist ip:port
  alsit_token: "" #alist token
search:
  alist_web: "https://" #你的alist域名
  per_page: 5 #搜索结果返回数量，默认5条
  z_url: true #是否开启直链
