bot:
  backup_time: '0'
  search:
    per_page: 5
    z_url: false
user:
  admin: 123456789 # 管理员用户id，可通过 https://t.me/getletbot 获取id
  member: []  # 允许使用bot的 用户、群组、频道（群组和频道id需要加上-100）可通过 https://t.me/getletbot 获取id
  alist_host: http://127.0.0.1:5244 # alist ip:port或alist域名，一般填域名即可
  alist_web: "https://" # 你的alist域名
  alist_token: "" # alist token
  bot_token: "" # bot的api token，从 @BotFather 获取
  api_id: "" # api_id、api_hash在 https://my.telegram.org/apps 获取
  api_hash: ""
proxy:
  scheme:  # 支持“socks4”、“socks5”和“http”，不填则不使用代理，例：http
  hostname: #例：127.0.0.1
  port: #例：7890
